apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: container-1
          securityContext:
            privileged: true

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
  labels:
    app: app-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
        - name: container-1
          securityContext:
            allowPrivilegeEscalation: true
