apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3
  labels:
    app: app-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-3
    spec:
      containers:
        - name: container-1
          securityContext:
            privileged: true
            allowPrivilegeEscalation: false

