name: Weaveworks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git clone git@github.com:MagalixTechnologies/policy-library -b flux-demo /tmp/policy-library
        
      - uses: ahsayde/weave-action@master
        with:
          path: entities/helm
          helm-values-file: entities/helm/values.yaml
          policies-path: /tmp/policy-library/policies
          remediate: false
          sarif-file: results.sarif

      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: results.sarif
