name: Weaveworks
on:
  pull_request:
    branches: [ master ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahsayde/weave-action@master
        with:
          path: entities/kustomize/overlays/test
          policies-path: policies
          remediate: true
          sarif-file: results.sarif

      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: results.sarif

