name: Weaveworks
on:
  pull_request:
    branches: [ master ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git clone https://oauth2:${{ secrets.CLONE_TOKEN }}@github.com/MagalixTechnologies/policy-library -b flux-demo
      - uses: ahsayde/weave-action@master
        with:
          path: entities/kubernetes
          policies-path: policy-library
          remediate: true
          sarif-file: results.sarif

      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: results.sarif
